import { PresetService } from '../types';

export const PRESET_SERVICES: PresetService[] = [
  {
    id: 'netflix',
    name: 'Netflix',
    categoryId: 'video',
    defaultAmount: 1590,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.netflix.com/youraccount',
    officialUrl: 'https://www.netflix.com',
    color: '#E50914',
    icon: 'Tv',
    description: '映画・ドラマ配信サービス',
    tipsForCanceling: '※ドコモ・au・SoftBank等の「回線セットプラン」で契約している場合、Netflix公式ではなく回線会社のマイページ（My docomo, My au等）から解約する必要があります。'
  },
  {
    id: 'u_next',
    name: 'U-NEXT',
    categoryId: 'video',
    defaultAmount: 2189,
    defaultCycle: 'monthly',
    cancelUrl: 'https://account.unext.jp/account/contract',
    officialUrl: 'https://video.unext.jp',
    color: '#00A0E9',
    icon: 'Tv',
    description: '動画見放題・雑誌読み放題',
    tipsForCanceling: '【ダークパターン注意】U-NEXTは「解約」と「退会」が別です。まず「契約内容の確認・解約」から月額プランを解約してください。光回線や店頭で加入した場合はプロバイダのマイページから解約が必要です。'
  },
  {
    id: 'amazon_prime',
    name: 'Amazon Prime',
    categoryId: 'lifestyle',
    defaultAmount: 600,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.amazon.co.jp/mc/pipelines/cancellation',
    officialUrl: 'https://www.amazon.co.jp',
    color: '#00A8E1',
    icon: 'ShoppingBag',
    description: '配送特典・Prime Video・Prime Music',
    tipsForCanceling: '「プライム会員情報」＞「会員資格を終了する」から数ステップで解約できます。'
  },
  {
    id: 'youtube_premium',
    name: 'YouTube Premium',
    categoryId: 'video',
    defaultAmount: 1280,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    officialUrl: 'https://www.youtube.com',
    color: '#FF0000',
    icon: 'Youtube',
    description: '広告なし再生・バックグラウンド再生',
    tipsForCanceling: 'ドコモ爆アゲ等の回線経由の場合はMy docomoから解約。iPhoneアプリから加入した場合はApple IDのサブスクリプションから解約。'
  },
  {
    id: 'spotify',
    name: 'Spotify Premium',
    categoryId: 'music',
    defaultAmount: 980,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.spotify.com/jp/account/overview/',
    officialUrl: 'https://www.spotify.com',
    color: '#1DB954',
    icon: 'Music',
    description: '音楽聴き放題・オフライン再生',
    tipsForCanceling: 'アカウントページ ＞「利用可能なプラン」＞「Premiumをキャンセル」を選択します。'
  },
  {
    id: 'chatgpt_plus',
    name: 'ChatGPT Plus',
    categoryId: 'ai_tools',
    defaultAmount: 3000,
    defaultCycle: 'monthly',
    cancelUrl: 'https://chatgpt.com/#settings/Subscription',
    officialUrl: 'https://chatgpt.com',
    color: '#10A37F',
    icon: 'Bot',
    description: 'OpenAI GPT-4o / 最新AIモデル利用',
    tipsForCanceling: '左下メニュー ＞「設定」＞「サブスクリプション」＞「プランの管理」＞「サブスクリプションをキャンセル」をクリック。'
  },
  {
    id: 'claude_pro',
    name: 'Claude Pro',
    categoryId: 'ai_tools',
    defaultAmount: 3000,
    defaultCycle: 'monthly',
    cancelUrl: 'https://claude.ai/settings/billing',
    officialUrl: 'https://claude.ai',
    color: '#D97706',
    icon: 'Sparkles',
    description: 'Anthropic Claude 3.5 Sonnet / 優先アクセス',
    tipsForCanceling: '設定 ＞ Billing ＞「Cancel Plan」から解約できます。'
  },
  {
    id: 'apple_one',
    name: 'Apple One',
    categoryId: 'entertainment',
    defaultAmount: 1200,
    defaultCycle: 'monthly',
    cancelUrl: 'https://finance-app.itunes.apple.com/account/subscriptions',
    officialUrl: 'https://www.apple.com/jp/apple-one/',
    color: '#A2AAAD',
    icon: 'Apple',
    description: 'Apple Music, TV+, Arcade, iCloud+ セット',
    tipsForCanceling: 'iPhone「設定」＞ 自分の名前 ＞「サブスクリプション」からワンタップで解約可能です。'
  },
  {
    id: 'icloud_plus',
    name: 'iCloud+ (50GB/200GB)',
    categoryId: 'cloud_storage',
    defaultAmount: 130,
    defaultCycle: 'monthly',
    cancelUrl: 'https://support.apple.com/ja-jp/HT207594',
    officialUrl: 'https://www.apple.com/jp/icloud/',
    color: '#0070C9',
    icon: 'Cloud',
    description: 'iPhone写真・バックアップ',
    tipsForCanceling: 'iPhone「設定」＞ 自分の名前 ＞「iCloud」＞「ストレージプランの管理」＞「ダウングレード」から解約。'
  },
  {
    id: 'disney_plus',
    name: 'Disney+ (ディズニープラス)',
    categoryId: 'video',
    defaultAmount: 990,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.disneyplus.com/account',
    officialUrl: 'https://www.disneyplus.com',
    color: '#113CCF',
    icon: 'Film',
    description: 'ディズニー、ピクサー、マーベル見放題',
    tipsForCanceling: '※ドコモ経由で登録した場合は「dアカウント」のマイページからの解約が必要です。'
  },
  {
    id: 'adobe_creative_cloud',
    name: 'Adobe Creative Cloud',
    categoryId: 'productivity',
    defaultAmount: 7780,
    defaultCycle: 'monthly',
    cancelUrl: 'https://account.adobe.com/plans',
    officialUrl: 'https://www.adobe.com',
    color: '#FF0000',
    icon: 'Palette',
    description: 'Photoshop, Illustrator, Premiere Proなど',
    tipsForCanceling: 'プラン管理 ＞「プランを解約」。※年間プラン月々払いの場合、解約違約金が発生する場合があるので注意。'
  },
  {
    id: 'github_copilot',
    name: 'GitHub Copilot',
    categoryId: 'productivity',
    defaultAmount: 1500,
    defaultCycle: 'monthly',
    cancelUrl: 'https://github.com/settings/billing/summary',
    officialUrl: 'https://github.com',
    color: '#24292F',
    icon: 'Code2',
    description: 'AIペアプログラミング支援ツール',
    tipsForCanceling: 'Settings ＞ Billing and plans ＞ Copilot ＞ Cancel subscription を選択。'
  },
  {
    id: 'lemino_premium',
    name: 'Leminoプレミアム (旧dTV)',
    categoryId: 'video',
    defaultAmount: 990,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.docomo.ne.jp/mydocomo/',
    officialUrl: 'https://lemino.docomo.ne.jp',
    color: '#FF5500',
    icon: 'Tv',
    description: 'ドコモ提供の動画見放題サービス',
    tipsForCanceling: '【抱き合わせ代表】My docomo ＞「ご契約内容確認・変更」＞「Leminoプレミアム」＞「解約」から手続き。'
  },
  {
    id: 'carrier_security_option',
    name: '回線・店頭抱き合わせオプション (安心パック/セキュリティ等)',
    categoryId: 'other',
    defaultAmount: 550,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.google.com/search?q=%E3%82%AD%E3%83%A3%E3%83%AA%E3%82%A2+%E6%8A%B1%E3%81%8D%E5%90%88%E3%82%8F%E3%81%9B+%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3+%E8%A7%A3%E7%B4%84',
    color: '#FF453A',
    icon: 'ShieldCheck',
    description: 'スマホや光回線の契約時に勝手につけられたオプション',
    tipsForCanceling: 'スマホ契約時や回線開通時に「初月無料だから」と付けられたオプション群です。各キャリアのマイページ（My docomo, My au, My SoftBank）から一括で解約できます。'
  },
  {
    id: 'dmm_tv',
    name: 'DMM TV (DMMプレミアム)',
    categoryId: 'video',
    defaultAmount: 550,
    defaultCycle: 'monthly',
    cancelUrl: 'https://premium.dmm.com/settings/service/',
    officialUrl: 'https://tv.dmm.com',
    color: '#FF4338',
    icon: 'Film',
    description: 'アニメ・エンタメ動画見放題',
    tipsForCanceling: 'DMMプレミアム利用状況 ＞「解約手続きへ」から進みます。'
  },
  {
    id: 'dazn',
    name: 'DAZN (ダゾーン)',
    categoryId: 'video',
    defaultAmount: 4200,
    defaultCycle: 'monthly',
    cancelUrl: 'https://www.dazn.com/ja-JP/myaccount/subscription',
    officialUrl: 'https://www.dazn.com',
    color: '#F8F8F8',
    icon: 'Activity',
    description: 'Jリーグ・プロ野球・欧州サッカー・F1生中継',
    tipsForCanceling: '※auやdocomo経由で契約した場合は各キャリアマイページから解約が必要です。'
  },
  {
    id: 'nintendo_switch_online',
    name: 'Nintendo Switch Online',
    categoryId: 'gaming',
    defaultAmount: 2400,
    defaultCycle: 'yearly',
    cancelUrl: 'https://ec.nintendo.com/membership',
    officialUrl: 'https://www.nintendo.co.jp/hardware/switch/onlineservice/',
    color: '#E60012',
    icon: 'Gamepad2',
    description: 'オンラインプレイ・セーブデータお預かり',
    tipsForCanceling: 'ニンテンドーアカウント設定 ＞ ショップメニュー ＞ 利用券の自動継続購入を停止。'
  },
  {
    id: 'chocozap',
    name: 'chocoZAP (チョコザップ)',
    categoryId: 'fitness',
    defaultAmount: 3278,
    defaultCycle: 'monthly',
    cancelUrl: 'https://chocozap.jp/',
    officialUrl: 'https://chocozap.jp',
    color: '#FFE600',
    icon: 'Dumbbell',
    description: '24時間利用可能コンビニジム',
    tipsForCanceling: 'チョコザップ公式アプリ ＞ メニュー ＞ 会員情報 ＞ プラン確認・変更 ＞「退会手続き」'
  }
];
