import { Subscription } from '../types';
import { formatCurrency } from './formatters';

/**
 * 日付文字列（YYYY-MM-DD）を iCalendar 形式（YYYYMMDD）に変換
 */
function formatDateToIcs(dateStr: string): string {
  return dateStr.replace(/-/g, '');
}

/**
 * Google カレンダーに追加するためのURLを生成
 */
export function getGoogleCalendarUrl(subscription: Subscription): string {
  const targetDate = subscription.isTrial && subscription.trialEndDate
    ? subscription.trialEndDate
    : subscription.nextBillingDate;

  const eventTitle = encodeURIComponent(
    subscription.isTrial
      ? `【解約期限】${subscription.name} 無料体験終了日`
      : `【更新日】${subscription.name} サブスク更新・請求日`
  );

  const icsDate = formatDateToIcs(targetDate);
  // 終日イベントの場合は YYYYMMDD/YYYYMMDD (翌日)
  const nextDay = new Date(targetDate);
  nextDay.setDate(nextDay.getDate() + 1);
  const icsNextDate = formatDateToIcs(nextDay.toISOString().split('T')[0]);

  const cycleText = subscription.billingCycle === 'yearly' ? '年額' : '月額';
  const notesText = subscription.notes ? `\nメモ: ${subscription.notes}` : '';
  const cancelUrlText = subscription.cancelUrl ? `\n解約ページ: ${subscription.cancelUrl}` : '';

  const details = encodeURIComponent(
    `サービス名: ${subscription.name}\n` +
    `請求金額: ${formatCurrency(subscription.amount)} (${cycleText})\n` +
    `次回更新日: ${targetDate}` +
    cancelUrlText +
    notesText +
    `\n\nGenerated by SubCut (サブスク断捨離アシスタント)`
  );

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${eventTitle}&dates=${icsDate}/${icsNextDate}&details=${details}`;
}

/**
 * iCalendar (.ics) ファイルを生成してダウンロード
 */
export function downloadIcsFile(subscription: Subscription): void {
  const targetDate = subscription.isTrial && subscription.trialEndDate
    ? subscription.trialEndDate
    : subscription.nextBillingDate;

  const icsDate = formatDateToIcs(targetDate);
  const nextDay = new Date(targetDate);
  nextDay.setDate(nextDay.getDate() + 1);
  const icsNextDate = formatDateToIcs(nextDay.toISOString().split('T')[0]);

  const eventTitle = subscription.isTrial
    ? `【解約期限】${subscription.name} 無料体験終了日`
    : `【更新日】${subscription.name} サブスク更新日`;

  const cycleText = subscription.billingCycle === 'yearly' ? '年額' : '月額';
  const notesText = subscription.notes ? `\\nメモ: ${subscription.notes}` : '';
  const cancelUrlText = subscription.cancelUrl ? `\\n解約URL: ${subscription.cancelUrl}` : '';

  const description = `サービス名: ${subscription.name}\\n` +
    `請求金額: ${formatCurrency(subscription.amount)} (${cycleText})\\n` +
    `更新日: ${targetDate}` +
    cancelUrlText +
    notesText +
    `\\n\\nSubCut サブスク断捨離アシスタント`;

  const nowIcs = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  const uid = `subcut-${subscription.id}-${Date.now()}@subcut.local`;

  // 3日前・前日のアラームブロック
  const alarms = ICS_ALARM_DAYS_BEFORE.map((days) => `
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:${subscription.name} の更新${days}日前リマインダー
TRIGGER:-P${days}D
END:VALARM`).join('');

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SubCut//Subscription Manager//JA',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${nowIcs}`,
    `DTSTART;VALUE=DATE:${icsDate}`,
    `DTEND;VALUE=DATE:${icsNextDate}`,
    `SUMMARY:${eventTitle}`,
    `DESCRIPTION:${description}`,
    subscription.cancelUrl ? `URL:${subscription.cancelUrl}` : '',
    alarms,
    'END:VEVENT',
    'END:VCALENDAR'
  ].filter(Boolean).join('\r\n');

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${subscription.name}_billing_reminder.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
